Config = Config or {}

Config.RosterLink = {
    ['police'] = 'https://docs.google.com/spreadsheets/d/1IVrqJFQ9_eH4A25cF7hQF37IsRX1IWF9/edit#gid=166055843',
    ['ambulance'] = 'https://docs.google.com/spreadsheets/d/1rJzFcMQkPh5sjOfg9iaqFjVYziG-aoezi_s1hRL_gow/edit#gid=361362235',
    ['bcso'] = 'https://docs.google.com/spreadsheets/d/1IVrqJFQ9_eH4A25cF7hQF37IsRX1IWF9/edit#gid=166055843',
    ['doj'] = 'https://docs.google.com/spreadsheets/d/1IVrqJFQ9_eH4A25cF7hQF37IsRX1IWF9/edit#gid=166055843',
}

Config.Fuel = "LegacyFuel" -- "LegacyFuel", "lj-fuel"

Config.PenalCodeTitles = {
    [1] = 'ПРЕСТЪПЛЕНИЯ СРЕЩУ ЧОВЕЧЕСТВОТО',
    [2] = 'ПРЕСТЪПЛЕНИЯ ВКЛЮЧВАЩИ КРАЖБИ',
    [3] = 'ПРЕСТЪПЛЕНИЯ ВКЛЮЧВАЩИ ИЗМАМИ',
    [4] = 'ПРЕСТЪПЛЕНИЯ ВКЛЮЧВАЩИ РАЗРУШАВАНЕ НА СОБСТВЕНОСТ',
    [5] = 'ПРЕСТЪПЛЕНИЯ ВКЛЮЧВАЩИ ПУБЛИЧНА АДМИНИСТРАЦИЯ',
    [6] = 'ПРЕСТЪПЛЕНИЯ СРЕЩУ ЛИЧНОСТТА',
    [7] = 'ПРЕСТЪПЛЕНИЯ СРЕЩУ ПУБЛИЧНАТА СИГУРНОСТ',
    [8] = 'ПРЕСТЪПЛЕНИЯ ВКЛЮЧВАЩИ УПРАВЛЕНИЕ НА МПС',
    [9] = 'ПРЕСТЪПЛЕНИЯ СРЕЩУ ДИВАТА ПРИРОДА',
}

Config.PenalCode = {
    [1] = {
        [1] = {title = 'Леко нападение', class = 'Нарушение', id = 'Чл. 1001', months = 5, fine = 500, color = 'green'},
        [2] = {title = 'Нападение', class = 'Престъпление', id = 'Чл. 1002', months = 10, fine = 650, color = 'orange'},
        [3] = {title = 'Агресивно поведение', class = 'Престъпление', id = 'Чл. 1003', months = 12, fine = 1150, color = 'orange'},
        [4] = {title = 'Нападение със смъртоносно оръжие', class = 'Углавно престъпление', id = 'Чл. 1004', months = 25, fine = 2500, color = 'red'},
        [5] = {title = 'Неволно убийство', class = 'Углавно престъпление', id = 'Чл. 1005', months = 30, fine = 6000, color = 'red'},
        [6] = {title = 'Непредумишлено убийство с МПС', class = 'Углавно престъпление', id = 'Чл. 1006', months = 15, fine = 2350, color = 'red'},
        [7] = {title = 'Опит за убийство на цивилен', class = 'Углавно престъпление', id = 'Чл. 1007', months = 23, fine = 5000, color = 'red'},
        [8] = {title = 'Убийство втора степен', class = 'Углавно престъпление', id = 'Чл. 1008', months = 28, fine = 5550, color = 'red'},
        [9] = {title = 'Съучастие в убийство от втора степен', class = 'Углавно престъпление', id = 'Чл. 1009', months = 20, fine = 3500, color = 'red'},
        [10] = {title = 'Убийство първа степен', class = 'Престъпление', id = 'Чл. 1010', months = 20, fine = 3850, color = 'red'},
        [11] = {title = 'Съучастие в убийство от първа степен', class = 'Углавно престъпление', id = 'Чл. 1011', months = 12, fine = 2475, color = 'red'},
        [12] = {title = 'Убийство на държавен служител или служител на мира', class = 'Углавно престъпление', id = 'Чл. 1012', months = 35, fine = 5000, color = 'red'},
        [13] = {title = 'Опит за убийство на държавен служител или служител на мира', class = 'Углавно престъпление', id = 'Чл. 1013', months = 25, fine = 3000, color = 'red'},
        [14] = {title = 'Съучастие в убийството на държавен служител или служител на мира', class = 'Углавно престъпление', id = 'Чл. 1014', months = 20, fine = 2850, color = 'red'},
        [15] = {title = 'Незаконно лишаване от свобода', class = 'Престъпление', id = 'Чл. 1015', months = 18, fine = 3000, color = 'orange'},
        [16] = {title = 'Отвличане', class = 'Углавно престъпление', id = 'Чл. 1016', months = 18, fine = 1500, color = 'orange'},
        [17] = {title = 'Опит за отвличане', class = 'Углавно престъпление', id = 'Чл. 1018', months = 15, fine = 850, color = 'orange'},
        [18] = {title = 'Престъпни заплахи', class = 'Престъпление', id = 'Чл. 1022', months = 5, fine = 850, color = 'orange'},
        [19] = {title = 'Безрасъдно застрашаване', class = 'Престъпление', id = 'Чл. 1023', months = 10, fine = 1250, color = 'orange'},
        [20] = {title = 'Престрелка между престъпна групировка', class = 'Углавно престъпление', id = 'Чл. 1024', months = 24, fine = 2500, color = 'red'},
        [21] = {title = 'Канибализъм', class = 'Углавно престъпление', id = 'Чл. 1025', months = 20, fine = 2500, color = 'red'},
        [22] = {title = 'Изтезание', class = 'Углавно престъпление', id = 'Чл. 1026', months = 35, fine = 3750, color = 'red'},
        [23] = {title = 'Следене', class = 'Престъпление', id = 'Чл. 1027', months = 0, fine = 875, color = 'orange'},
    },
    [2] = {
        [1] = {title = 'Дребна кражба', class = 'Нарушение', id = 'Чл. 2001', months = 0, fine = 500, color = 'green'},
        [2] = {title = 'Грабеж', class = 'Престъпление', id = 'Чл. 2002', months = 8, fine = 850, color = 'orange'},
        [3] = {title = 'Кражба на автомобил', class = 'Углавно престъпление', id = 'Чл. 2005', months = 7, fine = 985, color = 'red'},
        [4] = {title = 'Влизане с взлом', class = 'Престъпление', id = 'Чл. 2006', months = 9, fine = 990, color = 'orange'},
        [5] = {title = 'Обир', class = 'Углавно престъпление', id = 'Чл. 2007', months = 12, fine = 1350, color = 'red'},
        [6] = {title = 'Опит за извършване на обир', class = 'Углавно престъпление', id = 'Чл. 2009', months = 10, fine = 1150, color = 'red'},
        [7] = {title = 'Въоръжен обир', class = 'Углавно престъпление', id = 'Чл. 2010', months = 15, fine = 1650, color = 'red'},
        [8] = {title = 'Опит за извършване на въоръжен грабеж', class = 'Углавно престъпление', id = 'Чл. 2012', months = 12, fine = 1250, color = 'red'},
        [9] = {title = 'Грабеж в огромни количества', class = 'Углавно престъпление', id = 'Чл. 2013', months = 20, fine = 4850, color = 'red'},
        [10] = {title = 'Напускане на обект без заплащане', class = 'Нарушение', id = 'Чл. 2014', months = 0, fine = 500, color = 'green'},
        [11] = {title = 'Притежание на нелегална валута', class = 'Престъпление', id = 'Чл. 2015', months = 8, fine = 850, color = 'orange'},
        [12] = {title = 'Притежание на служебно оръжие', class = 'Углавно престъпление', id = 'Чл. 2016', months = 10, fine = 1250, color = 'red'},
        [13] = {title = 'Притежание на вещи, използвани за извършване на престъпление', class = 'Престъпление', id = 'Чл. 2017', months = 5, fine = 1000, color = 'orange'},
        [14] = {title = 'Продаване на вещи, използвани за извършване на престъпление', class = 'Felony', id = 'Чл. 2018', months = 5, fine = 1000, color = 'orange'},
        [15] = {title = 'Кражба на летателно превозно средство', class = 'Углавно престъпление', id = 'Чл. 2019', months = 8, fine = 1500, color = 'red'},
    },
    [3] = {
        [1] = {title = 'Представяне за служител на реда или държавен служител', class = 'Престъпление', id = 'Чл. 3002', months = 10, fine = 1280, color = 'orange'},
        [2] = {title = 'Представяне за съдия', class = 'Престъпление', id = 'Чл. 3003', months = 12, fine = 1350, color = 'orange'},
        [3] = {title = 'Притежание на открадната самоличност', class = 'Престъпление', id = 'Чл. 3004', months = 5, fine = 980, color = 'orange'},
        [4] = {title = 'Притежание на откраднати правителствени документи', class = 'Престъпление', id = 'Чл. 3005', months = 8, fine = 1550, color = 'orange'},
        [5] = {title = 'Изнудване', class = 'Престъпление', id = 'Чл. 3006', months = 8, fine = 920, color = 'orange'},
        [6] = {title = 'Измама', class = 'Престъпление', id = 'Чл. 3007', months = 9, fine = 975, color = 'orange'},
        [7] = {title = 'Фалшификация', class = 'Престъпление', id = 'Чл. 3008', months = 9, fine = 975, color = 'orange'},
        [8] = {title = 'Пране на пари', class = 'Углавно престъпление', id = 'Чл. 3009', months = 15, fine = 2850, color = 'red'},
    },
    [4] = {
        [1] = {title = 'Навлизане и/или безпокойство', class = 'Нарушение', id = 'Чл. 4001', months = 5, fine = 750, color = 'green'},
        [2] = {title = 'Углавно навлизане и/или безпокойство', class = 'Углавно престъпление', id = 'Чл. 4002', months = 10, fine = 1375, color = 'red'},
        [3] = {title = 'Палеж', class = 'Углавно престъпление', id = 'Чл. 4003', months = 15, fine = 1500, color = 'orange'},
        [4] = {title = 'Вандализъм', class = 'Нарушение', id = 'Чл. 4004', months = 0, fine = 650, color = 'green'},
        [5] = {title = 'Вандализъм върху държавна собственост', class = 'Престъпление', id = 'Чл. 4005', months = 20, fine = 1500, color = 'orange'},
        [6] = {title = 'Незаконно изхърляне на отпадъци', class = 'Нарушение', id = 'Чл. 4006', months = 0, fine = 450, color = 'green'},
    },
    [5] = {
        [1] = {title = 'Подкуп на държавен служител', class = 'Углавно престъпление', id = 'Чл. 5001', months = 14, fine = 2300, color = 'red'},
        [2] = {title = 'Притежание на контрабанда в правителствено съоръжение', class = 'Углавно престъпление', id = 'Чл. 5003', months = 10, fine = 2300, color = 'red'},
        [3] = {title = 'Престъпно притежание на откраднато имущество', class = 'Престъпление', id = 'Чл. 5004', months = 7, fine = 830, color = 'orange'},
        [4] = {title = 'Бягство от полиция', class = 'Углавно престъпление', id = 'Чл. 5005', months = 12, fine = 1115, color = 'red'},
        [5] = {title = 'Бягство от затвора', class = 'Углавно престъпление', id = 'Чл. 5006', months = 18, fine = 2585, color = 'red'},
        [6] = {title = 'Опит за бягство от затвора', class = 'Углавно престъпление', id = 'Чл. 5008', months = 14, fine = 2200, color = 'red'},
        [7] = {title = 'Лъжесвидетелстване', class = 'Престъпление', id = 'Чл. 5009', months = 3, fine = 850, color = 'orange'},
        [8] = {title = 'Нарушаване на ограничителна заповед', class = 'Престъпление', id = 'Чл. 5010', months = 8, fine = 1400, color = 'orange'},
        [9] = {title = 'Присвояване', class = 'Престъпление', id = 'Чл. 5011', months = 5, fine = 1000, color = 'orange'},
        [10] = {title = 'Неправилно използване на спешна помощ', class = 'Нарушение', id = 'Чл. 5013', months = 0, fine = 850, color = 'green'},
        [11] = {title = 'Конспирация', class = 'Престъпление', id = 'Чл. 5014', months = 10, fine = 450, color = 'orange'},
        [12] = {title = 'Нарушаване на съдебния ред', class = 'Престъпление', id = 'Чл. 5015', months = 0, fine = 950, color = 'orange'},
        [13] = {title = 'Неявяване при съдебен процес', class = 'Престъпление', id = 'Чл. 5016', months = 15, fine = 2500, color = 'orange'},
        [14] = {title = 'Неуважение към съда', class = 'Престъпление', id = 'Чл. 5017', months = 0, fine = 2300, color = 'orange'},
        [15] = {title = 'Съпротива при арест', class = 'Престъпление', id = 'Чл. 5018', months = 8, fine = 1850, color = 'orange'},
        [16] = {title = 'Неуважение към служител на реда', class = 'Престъпление', id = 'Чл. 5019', months = 0, fine = 1400, color = 'orange'},
        [17] = {title = 'Нарушение на нощната тишина', class = 'Престъпление', id = 'Чл. 5020', months = 0, fine = 760, color = 'orange'},
        [18] = {title = 'Непритежание на лични документи', class = 'Нарушение', id = 'Чл. 5021', months = 0, fine = 1250, color = 'green'},
        [19] = {title = 'Неизпълнение на полицейско разпореждане', class = 'Нарушение', id = 'Чл. 5022', months = 0, fine = 500, color = 'green'},
    },
    [6] = {
        [1] = {title = 'Притежание на марихуана', class = 'Престъпление', id = 'Чл. 7001', months = 6, fine = 900, color = 'orange'},
        [2] = {title = 'Углавно притежание на марихуана', class = 'Углавно престъпление', id = 'Чл. 7002', months = 15, fine = 1460, color = 'red'},
        [3] = {title = 'Отглеждане на марихуана', class = 'Престъпление', id = 'Чл. 7003', months = 15, fine = 1385, color = 'green'},
        [4] = {title = 'Углавно отглеждане на марихуана', class = 'Углавно престъпление', id = 'Чл. 7004', months = 18, fine = 1870, color = 'red'},
        [5] = {title = 'Притежание на марихуана с намерение за разпространение', class = 'Углавно престъпление', id = 'Чл. 7005', months = 18, fine = 2500, color = 'red'},
        [6] = {title = 'Притежание на кокайн', class = 'Престъпление', id = 'Чл. 7006', months = 8, fine = 1000, color = 'orange'},
        [7] = {title = 'Углавно притежание на кокайн', class = 'Углавно престъпление', id = 'Чл. 7007', months = 15, fine = 1460, color = 'red'},
        [8] = {title = 'Притежание на кокайн с намерение за разпространение', class = 'Углавно престъпление', id = 'Чл. 7008', months = 18, fine = 2500, color = 'red'},
        [9] = {title = 'Притежание на метаамфетамин', class = 'Престъпление', id = 'Чл. 7009', months = 5, fine = 890, color = 'orange'},
        [10] = {title = 'Углавно притежание на метаамфетамин', class = 'Углавно престъпление', id = 'Чл. 7010', months = 15, fine = 1460, color = 'red'},
        [11] = {title = 'Притежание на метаамфетамин с намерение за разпространение', class = 'Углавно престъпление', id = 'Чл. 7011', months = 18, fine = 2500, color = 'red'},
        [12] = {title = 'Притежание на оксикодон/викодин', class = 'Престъпление', id = 'Чл. 7012', months = 10, fine = 890, color = 'orange'},
        [13] = {title = 'Углавно притежание на оксикодон/викодин', class = 'Углавно престъпление', id = 'Чл. 7013', months = 15, fine = 1460, color = 'red'},
        [14] = {title = 'Притежание на оксикодон/викодин с намерение за разпространение', class = 'Угвално престъпление', id = 'Чл. 7014', months = 18, fine = 2500, color = 'red'},
        [15] = {title = 'Притежание на екстази', class = 'Престъпление', id = 'Чл. 7015', months = 10, fine = 890, color = 'orange'},
        [16] = {title = 'Углавно притежание на екстази', class = 'Углавно престъпление', id = 'Чл. 7016', months = 15, fine = 1460, color = 'red'},
        [17] = {title = 'Притежание на екстази с намерение за разпространение', class = 'Углавно престъпление', id = 'Чл. 7017', months = 18, fine = 2500, color = 'red'},
        [18] = {title = 'Притежание на опиум', class = 'Престъпление', id = 'Чл. 7018', months = 10, fine = 890, color = 'orange'},
        [19] = {title = 'Углавно притежание на опиум', class = 'Углавно престъпление', id = 'Чл. 7019', months = 10, fine = 1460, color = 'red'},
        [20] = {title = 'Притежание на опиум с намерение за разпространение', class = 'Углавно престъпление', id = 'Чл. 7020', months = 18, fine = 2500, color = 'red'},
        [21] = {title = 'Притежание на адерал', class = 'Престъпление', id = 'Чл. 7021', months = 10, fine = 890, color = 'orange'},
        [22] = {title = 'Углавно притежание на адерал', class = 'Углавно престъпление', id = 'Чл. 7022', months = 10, fine = 1460, color = 'red'},
        [23] = {title = 'Притежание на адерал с намерение за разпространение', class = 'Углавно престъпление', id = 'Чл. 7023', months = 18, fine = 2500, color = 'red'},
        [24] = {title = 'Притежание на ксанакс', class = 'Престъпление', id = 'Чл. 7024', months = 10, fine = 890, color = 'orange'},
        [25] = {title = 'Углавно притежание на ксанакс', class = 'Углавно престъпление', id = 'Чл. 7025', months = 10, fine = 890, color = 'orange'},
        [26] = {title = 'Притежание на ксанакс с намерение за разпространение', class = 'Углавно престъпление', id = 'Чл. 7026', months = 18, fine = 2500, color = 'red'},
        [27] = {title = 'Разпространяване на контролирани субстанции', class = 'Престъпление', id = 'Чл. 7033', months = 12, fine = 1650, color = 'orange'},
        [28] = {title = 'Разпространение на наркотици', class = 'Углавно престъпление', id = 'Чл. 7034', months = 12, fine = 1650, color = 'red'},
        [29] = {title = 'Оскверняване на човешки труп', class = 'Углавно престъпление', id = 'Чл. 7035', months = 20, fine = 2850, color = 'red'},
        [30] = {title = 'Публична интоксикация', class = 'Нарушение', id = 'Чл. 7036', months = 0, fine = 885, color = 'green'},
        [31] = {title = 'Непристойно поведение', class = 'Нарушение', id = 'Чл. 7037', months = 0, fine = 800, color = 'green'},
    },
    [7] = {
        [1] = {title = 'Нелегално притежание на огнестрелно оръжие от клас A', class = 'Углавно престъпление', id = 'Чл. 8001', months = 18, fine = 2500, color = 'red'},
        [2] = {title = 'Нелегално притежание на огнестрелно оръжие от клас B', class = 'Углавно престъпление', id = 'Чл. 8002', months = 20, fine = 3500, color = 'red'},
        [3] = {title = 'Нелегално притежание на огнестрелно оръжие от клас C', class = 'Углавно престъпление', id = 'Чл. 8003', months = 25, fine = 4500, color = 'red'},
        [4] = {title = 'Нелегално притежание на огнестрелно оръжие от клас D', class = 'Углавно престъпление', id = 'Чл. 8004', months = 30, fine = 5000, color = 'red'},
        [5] = {title = 'Нелегално разпространение на огнестрелно оръжие от клас A', class = 'Углавно престъпление', id = 'Чл. 8005', months = 15, fine = 1500, color = 'red'},
        [6] = {title = 'Нелегално разпространение на огнестрелно оръжие от клас B', class = 'Углавно престъпление', id = 'Чл. 8006', months = 25, fine = 3500, color = 'red'},
        [7] = {title = 'Нелегално разпространение на огнестрелно оръжие от клас C', class = 'Углавно престъпление', id = 'Чл. 8007', months = 30, fine = 4850, color = 'red'},
        [8] = {title = 'Нелегално разпространение на огнестрелно оръжие от клас D', class = 'Углавно престъпление', id = 'Чл. 8008', months = 35, fine = 5250, color = 'red'},
        [9] = {title = 'Нелегално използване на огнестрелно оръжие', class = 'Престъпление', id = 'Чл. 8009', months = 8, fine = 980, color = 'orange'},
        [10] = {title = 'Нелегално притежание на модификации за огнестрелно оръжие', class = 'Престъпление', id = 'Чл. 8010', months = 9, fine = 990, color = 'orange'},
        [11] = {title = 'Разпространение на огнестрелни оръжия', class = 'Углавно престъпление', id = 'Чл. 8011', months = 18, fine = 3000, color = 'red'},
        [12] = {title = 'Размахване на огнестрелно оръжие на публично място', class = 'Нарушение', id = 'Чл. 8012', months = 0, fine = 1200, color = 'green'},
        [13] = {title = 'Пилотиране над ограничено въздушно пространство', class = 'Углавно престъпление', id = 'Чл. 8014', months = 8, fine = 1250, color = 'red'},
        [14] = {title = 'Неправилно пресичане', class = 'Нарушение', id = 'Чл. 8015', months = 0, fine = 450, color = 'green'},
        [15] = {title = 'Незаконно използване на експлозиви', class = 'Углавно престъпление', id = 'Чл. 8016', months = 14, fine = 2300, color = 'red'},
    },
    [8] = {
        [1] = {title = 'Шофиране под въздействието на алкохол', class = 'Престъпление', id = 'Чл. 9001', months = 5, fine = 780, color = 'orange'},
        [2] = {title = 'Неподчинение на полицейско разпореждане', class = 'Престъпление', id = 'Чл. 9002', months = 6, fine = 820, color = 'orange'},
        [3] = {title = 'Безрасъдно шофиране', class = 'Углавно престъпление', id = 'Чл. 9003', months = 8, fine = 950, color = 'red'},
        [4] = {title = 'Неспиране на полицейски сигнал', class = 'Нарушение', id = 'Чл. 9004', months = 0, fine = 710, color = 'green'},
        [5] = {title = 'Неспиране на червен светофар', class = 'Нарушение', id = 'Чл. 9005', months = 0, fine = 550, color = 'green'},
        [6] = {title = 'Неизправно моторно превозно средство', class = 'Нарушение', id = 'Чл. 9006', months = 0, fine = 480, color = 'green'},
        [7] = {title = 'Небрежно шофиране', class = 'Нарушение', id = 'Чл. 9007', months = 0, fine = 380, color = 'green'},
        [8] = {title = 'Агресивно шофиране', class = 'Нарушение', id = 'Чл. 9008', months = 10, fine = 870, color = 'orange'},
        [9] = {title = 'Превишаване на скоростта (Първа степен)', class = 'Нарушение', id = 'Чл. 9009', months = 0, fine = 480, color = 'green'},
        [10] = {title = 'Превишаване на скоростта (Втора степен)', class = 'Нарушение', id = 'Чл. 9010', months = 0, fine = 790, color = 'green'},
        [11] = {title = 'Превишаване на скоростта (Трета степен)', class = 'Нарушение', id = 'Чл. 9011', months = 0, fine = 1100, color = 'green'},
        [12] = {title = 'Управление на МПС без СУМПС', class = 'Нарушение', id = 'Чл. 9012', months = 0, fine = 680, color = 'green'},
        [13] = {title = 'Нелегален обратен завой', class = 'Нарушение', id = 'Чл. 9013', months = 0, fine = 500, color = 'green'},
        [14] = {title = 'Неправилно пресичане', class = 'Нарушение', id = 'Чл. 9014', months = 0, fine = 300, color = 'green'},
        [15] = {title = 'Неспазване на лента на движение', class = 'Нарушение', id = 'Чл. 9015', months = 0, fine = 490, color = 'green'},
        [16] = {title = 'Нелегален завой', class = 'Нарушение', id = 'Чл. 9016', months = 0, fine = 475, color = 'green'},
        [17] = {title = 'Неспиране на знак за стоп', class = 'Нарушение', id = 'Чл. 9017', months = 0, fine = 385, color = 'green'},
        [18] = {title = 'Неправилно паркиране', class = 'Нарушение', id = 'Чл. 9018', months = 0, fine = 680, color = 'green'},
        [19] = {title = 'Бягство от ПТП', class = 'Престъпление', id = 'Чл. 9019', months = 5, fine = 980, color = 'orange'},
        [20] = {title = 'Шофиране без пуснати светлини', class = 'Нарушение', id = 'Чл. 9020', months = 0, fine = 475, color = 'green'},
        [21] = {title = 'Участие в улично състезание', class = 'Углавно престъпление', id = 'Чл. 9021', months = 8, fine = 2100, color = 'red'},
        [22] = {title = 'Пилотиране без необходим лиценз', class = 'Углавно престъпление', id = 'Чл. 9022', months = 5, fine = 2150, color = 'red'},
        [23] = {title = 'Незаконно използване на моторно превозно средство', class = 'Престъпление', id = 'Чл. 9023', months = 6, fine = 975, color = 'orange'},
    },
    [9] = {
        [1] = {title = 'Ловуване в ограничена зона', class = 'Нарушение', id = 'Чл. 10001', months = 0, fine = 850, color = 'green'},
        [2] = {title = 'Нелегално ловуване', class = 'Нарушение', id = 'Чл. 10002', months = 0, fine = 1000, color = 'green'},
        [3] = {title = 'Жестокост над животно', class = 'Престъпление', id = 'Чл. 10003', months = 8, fine = 1680, color = 'orange'},
        [4] = {title = 'Ловуване с неправилно оръжие', class = 'Престъпление', id = 'Чл. 10004', months = 5, fine = 890, color = 'orange'},
        [5] = {title = 'Ловуване извън часовото време', class = 'Нарушение', id = 'Чл. 10005', months = 0, fine = 650, color = 'green'},
        [6] = {title = 'Прекален лов', class = 'Престъпление', id = 'Чл. 10006', months = 0, fine = 1650, color = 'orange'},
        [7] = {title = 'Бракониерство', class = 'Углавно престъпление', id = 'Чл. 10007', months = 10, fine = 1385, color = 'red'},
    }
}

Config.PoliceJobs = {
    ['police'] = true,
    ['lspd'] = true,
    ['bcso'] = true,
    ['sast'] = true,
    ['sasp'] = true,
    ['doc'] = true,
    ['sapr'] = true,
    ['pa'] = true -- yucky
}

Config.AmbulanceJobs = {
    ['ambulance'] = true,
    ['doctor'] = true
}

Config.DojJobs = {
    ['lawyer'] = true,
}

-- Leave my hacky code alone ya goblins
Config.AllowedJobs = {}
for index, value in pairs(Config.PoliceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.AmbulanceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.DojJobs) do
    Config.AllowedJobs[index] = value
end
-- Leave my hacky code alone ya goblins

Config.LogPerms = {
	['ambulance'] = {
		[9] = true,
        [10] = true,
	},
	['police'] = {
		[8] = true,
        [10] = true,
	},
}

Config.ColorNames = {
    [0] = "Metallic Black",
    [1] = "Metallic Graphite Black",
    [2] = "Metallic Black Steel",
    [3] = "Metallic Dark Silver",
    [4] = "Metallic Silver",
    [5] = "Metallic Blue Silver",
    [6] = "Metallic Steel Gray",
    [7] = "Metallic Shadow Silver",
    [8] = "Metallic Stone Silver",
    [9] = "Metallic Midnight Silver",
    [10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",
    [12] = "Matte Black",
    [13] = "Matte Gray",
    [14] = "Matte Light Grey",
    [15] = "Util Black",
    [16] = "Util Black Poly",
    [17] = "Util Dark silver",
    [18] = "Util Silver",
    [19] = "Util Gun Metal",
    [20] = "Util Shadow Silver",
    [21] = "Worn Black",
    [22] = "Worn Graphite",
    [23] = "Worn Silver Grey",
    [24] = "Worn Silver",
    [25] = "Worn Blue Silver",
    [26] = "Worn Shadow Silver",
    [27] = "Metallic Red",
    [28] = "Metallic Torino Red",
    [29] = "Metallic Formula Red",
    [30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",
    [32] = "Metallic Garnet Red",
    [33] = "Metallic Desert Red",
    [34] = "Metallic Cabernet Red",
    [35] = "Metallic Candy Red",
    [36] = "Metallic Sunrise Orange",
    [37] = "Metallic Classic Gold",
    [38] = "Metallic Orange",
    [39] = "Matte Red",
    [40] = "Matte Dark Red",
    [41] = "Matte Orange",
    [42] = "Matte Yellow",
    [43] = "Util Red",
    [44] = "Util Bright Red",
    [45] = "Util Garnet Red",
    [46] = "Worn Red",
    [47] = "Worn Golden Red",
    [48] = "Worn Dark Red",
    [49] = "Metallic Dark Green",
    [50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",
    [52] = "Metallic Olive Green",
    [53] = "Metallic Green",
    [54] = "Metallic Gasoline Blue Green",
    [55] = "Matte Lime Green",
    [56] = "Util Dark Green",
    [57] = "Util Green",
    [58] = "Worn Dark Green",
    [59] = "Worn Green",
    [60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",
    [62] = "Metallic Dark Blue",
    [63] = "Metallic Saxony Blue",
    [64] = "Metallic Blue",
    [65] = "Metallic Mariner Blue",
    [66] = "Metallic Harbor Blue",
    [67] = "Metallic Diamond Blue",
    [68] = "Metallic Surf Blue",
    [69] = "Metallic Nautical Blue",
    [70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",
    [72] = "Metallic Spinnaker Blue",
    [73] = "Metallic Ultra Blue",
    [74] = "Metallic Bright Blue",
    [75] = "Util Dark Blue",
    [76] = "Util Midnight Blue",
    [77] = "Util Blue",
    [78] = "Util Sea Foam Blue",
    [79] = "Uil Lightning blue",
    [80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",
    [82] = "Matte Dark Blue",
    [83] = "Matte Blue",
    [84] = "Matte Midnight Blue",
    [85] = "Worn Dark blue",
    [86] = "Worn Blue",
    [87] = "Worn Light blue",
    [88] = "Metallic Taxi Yellow",
    [89] = "Metallic Race Yellow",
    [90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",
    [92] = "Metallic Lime",
    [93] = "Metallic Champagne",
    [94] = "Metallic Pueblo Beige",
    [95] = "Metallic Dark Ivory",
    [96] = "Metallic Choco Brown",
    [97] = "Metallic Golden Brown",
    [98] = "Metallic Light Brown",
    [99] = "Metallic Straw Beige",
    [100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",
    [102] = "Metallic Beechwood",
    [103] = "Metallic Dark Beechwood",
    [104] = "Metallic Choco Orange",
    [105] = "Metallic Beach Sand",
    [106] = "Metallic Sun Bleeched Sand",
    [107] = "Metallic Cream",
    [108] = "Util Brown",
    [109] = "Util Medium Brown",
    [110] = "Util Light Brown",
    [111] = "Metallic White",
    [112] = "Metallic Frost White",
    [113] = "Worn Honey Beige",
    [114] = "Worn Brown",
    [115] = "Worn Dark Brown",
    [116] = "Worn straw beige",
    [117] = "Brushed Steel",
    [118] = "Brushed Black steel",
    [119] = "Brushed Aluminium",
    [120] = "Chrome",
    [121] = "Worn Off White",
    [122] = "Util Off White",
    [123] = "Worn Orange",
    [124] = "Worn Light Orange",
    [125] = "Metallic Securicor Green",
    [126] = "Worn Taxi Yellow",
    [127] = "police car blue",
    [128] = "Matte Green",
    [129] = "Matte Brown",
    [130] = "Worn Orange",
    [131] = "Matte White",
    [132] = "Worn White",
    [133] = "Worn Olive Army Green",
    [134] = "Pure White",
    [135] = "Hot Pink",
    [136] = "Salmon pink",
    [137] = "Metallic Vermillion Pink",
    [138] = "Orange",
    [139] = "Green",
    [140] = "Blue",
    [141] = "Mettalic Black Blue",
    [142] = "Metallic Black Purple",
    [143] = "Metallic Black Red",
    [144] = "Hunter Green",
    [145] = "Metallic Purple",
    [146] = "Metaillic V Dark Blue",
    [147] = "MODSHOP BLACK1",
    [148] = "Matte Purple",
    [149] = "Matte Dark Purple",
    [150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",
    [152] = "Matte Olive Drab",
    [153] = "Matte Desert Brown",
    [154] = "Matte Desert Tan",
    [155] = "Matte Foilage Green",
    [156] = "DEFAULT ALLOY COLOR",
    [157] = "Epsilon Blue",
    [158] = "Unknown",
}

Config.ColorInformation = {
    [0] = "black",
    [1] = "black",
    [2] = "black",
    [3] = "darksilver",
    [4] = "silver",
    [5] = "bluesilver",
    [6] = "silver",
    [7] = "darksilver",
    [8] = "silver",
    [9] = "bluesilver",
    [10] = "darksilver",
    [11] = "darksilver",
    [12] = "matteblack",
    [13] = "gray",
    [14] = "lightgray",
    [15] = "black",
    [16] = "black",
    [17] = "darksilver",
    [18] = "silver",
    [19] = "utilgunmetal",
    [20] = "silver",
    [21] = "black",
    [22] = "black",
    [23] = "darksilver",
    [24] = "silver",
    [25] = "bluesilver",
    [26] = "darksilver",
    [27] = "red",
    [28] = "torinored",
    [29] = "formulared",
    [30] = "blazered",
    [31] = "gracefulred",
    [32] = "garnetred",
    [33] = "desertred",
    [34] = "cabernetred",
    [35] = "candyred",
    [36] = "orange",
    [37] = "gold",
    [38] = "orange",
    [39] = "red",
    [40] = "mattedarkred",
    [41] = "orange",
    [42] = "matteyellow",
    [43] = "red",
    [44] = "brightred",
    [45] = "garnetred",
    [46] = "red",
    [47] = "red",
    [48] = "darkred",
    [49] = "darkgreen",
    [50] = "racingreen",
    [51] = "seagreen",
    [52] = "olivegreen",
    [53] = "green",
    [54] = "gasolinebluegreen",
    [55] = "mattelimegreen",
    [56] = "darkgreen",
    [57] = "green",
    [58] = "darkgreen",
    [59] = "green",
    [60] = "seawash",
    [61] = "midnightblue",
    [62] = "darkblue",
    [63] = "saxonyblue",
    [64] = "blue",
    [65] = "blue",
    [66] = "blue",
    [67] = "diamondblue",
    [68] = "blue",
    [69] = "blue",
    [70] = "brightblue",
    [71] = "purpleblue",
    [72] = "blue",
    [73] = "ultrablue",
    [74] = "brightblue",
    [75] = "darkblue",
    [76] = "midnightblue",
    [77] = "blue",
    [78] = "blue",
    [79] = "lightningblue",
    [80] = "blue",
    [81] = "brightblue",
    [82] = "mattedarkblue",
    [83] = "matteblue",
    [84] = "matteblue",
    [85] = "darkblue",
    [86] = "blue",
    [87] = "lightningblue",
    [88] = "yellow",
    [89] = "yellow",
    [90] = "bronze",
    [91] = "yellow",
    [92] = "lime",
    [93] = "champagne",
    [94] = "beige",
    [95] = "darkivory",
    [96] = "brown",
    [97] = "brown",
    [98] = "lightbrown",
    [99] = "beige",
    [100] = "brown",
    [101] = "brown",
    [102] = "beechwood",
    [103] = "beechwood",
    [104] = "chocoorange",
    [105] = "yellow",
    [106] = "yellow",
    [107] = "cream",
    [108] = "brown",
    [109] = "brown",
    [110] = "brown",
    [111] = "white",
    [112] = "white",
    [113] = "beige",
    [114] = "brown",
    [115] = "brown",
    [116] = "beige",
    [117] = "steel",
    [118] = "blacksteel",
    [119] = "aluminium",
    [120] = "chrome",
    [121] = "wornwhite",
    [122] = "offwhite",
    [123] = "orange",
    [124] = "lightorange",
    [125] = "green",
    [126] = "yellow",
    [127] = "blue",
    [128] = "green",
    [129] = "brown",
    [130] = "orange",
    [131] = "white",
    [132] = "white",
    [133] = "darkgreen",
    [134] = "white",
    [135] = "pink",
    [136] = "pink",
    [137] = "pink",
    [138] = "orange",
    [139] = "green",
    [140] = "blue",
    [141] = "blackblue",
    [142] = "blackpurple",
    [143] = "blackred",
    [144] = "darkgreen",
    [145] = "purple",
    [146] = "darkblue",
    [147] = "black",
    [148] = "purple",
    [149] = "darkpurple",
    [150] = "red",
    [151] = "darkgreen",
    [152] = "olivedrab",
    [153] = "brown",
    [154] = "tan",
    [155] = "green",
    [156] = "silver",
    [157] = "blue",
    [158] = "black",
}

Config.ClassList = {
    [0] = "Compact",
    [1] = "Sedan",
    [2] = "SUV",
    [3] = "Coupe",
    [4] = "Muscle",
    [5] = "Sport Classic",
    [6] = "Sport",
    [7] = "Super",
    [8] = "Motorbike",
    [9] = "Off-Road",
    [10] = "Industrial",
    [11] = "Utility",
    [12] = "Van",
    [13] = "Bike",
    [14] = "Boat",
    [15] = "Helicopter",
    [16] = "Plane",
    [17] = "Service",
    [18] = "Emergency",
    [19] = "Military",
    [20] = "Commercial",
    [21] = "Train"
}

function GetJobType(job)
	if Config.PoliceJobs[job] then
		return 'police'
	elseif Config.AmbulanceJobs[job] then
		return 'ambulance'
	elseif Config.DojJobs[job] then
		return 'doj'
	else
		return nil
	end
end

-- this is a hack, because the qb-menu in qb-policejob populates an impound location and passed it through to the event.
-- if this impound locations are changed in qb-policejob, they must also be changed here.
Config.ImpoundLocations = { 
    [1] = vector4(436.68, -1007.42, 27.32, 180.0),
    [2] = vector4(-436.14, 5982.63, 31.34, 136.0),
}